[package]
name = "muslbuild"
version = "0.1.0"
authors = ["michael-grunder <michael.grunder@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdkafka = "0.21.0"
rdkafka-sys = "1.0.0"
